@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jan 15 17:31:11 +0300 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim TestBench_behav -key {Behavioral:sim_1:Functional:TestBench} -tclbatch TestBench.tcl -view C:/Users/Samet/Desktop/RISC_16bit_Processor/project_1/TestBench_behav.wcfg -log simulate.log"
call xsim  TestBench_behav -key {Behavioral:sim_1:Functional:TestBench} -tclbatch TestBench.tcl -view C:/Users/Samet/Desktop/RISC_16bit_Processor/project_1/TestBench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
